Fix fatal alert: protocol_version with TLSv1 clients.
Netty 4.0.35.Final rejects TLSv1 client connections with a 
javax.net.ssl.SSLException: Received fatal alert: protocol_version. So
the test client has to use the TLSv1.2 protocol.

Conflicts:
	pom.xml